
const productdata = [
    {
        id:0,
        productname:"ONNIX Men Kurta and Pyjama Set Cotton",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B08NRLJC9D&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/3GhuTZY",
    },
    {
        id:1,
        productname:"Brand Boy Men's Ethnic Wear Sherwani Wedding Dress Set",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B094YJHW79&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/3G8K5c5",
    },
    {
        id:2,
        productname:"Vastramay Men's Beige Cotton Silk Blend Kurta and Pyjama Set",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B07CPV9SC5&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/3E6Luho",
    },
    {
        id:3,
        productname:"Larwa Men's Dupion Silk Kurta Dhoti Set Special for Diwali Size 40",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B01GECJ670&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/3py5DZx",
},
{
        id:4,
        productname:"Vastramay Men's Black Cotton Silk Blend Kurta and Dhoti Pant Set",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B07D8VCB1Q&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/3pxVSuI",
},
{
        id:5,
        productname:"VASTRAMAY Men's Cotton Blend Pathani Kurta",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B07WJLD2FB&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/3vCvFMm",
},
{
        id:6,
        productname:"SG RAJASAHAB Mens Sherwani Set",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B07N8PCY5G&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/3nFeyGn",
},
{
        id:7,
        productname:"ANIL KUMAR AJIT KUMAR Self Design Cotton Blended Sherwani (Size:S-XXL)",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B09CQGT2GZ&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/3BbxAIO",
},
{
        id:8,
        productname:"Vastramay Men's Gold Cotton Silk Blend Sherwani Set",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B071NTYW2G&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/2Zn7eXC",
},
{
        id:9,
        productname:"VASTRAMAY Men Cotton Silk Kurta and Pyjama Set (Coffee_VASMKCO001nPCO)",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B07H34DC4W&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/2ZsBjF4",
},
{
        id:10,
        productname:"Vastramay Mens Cotton Silk Kurta, Waistcoat and Pyjama Set (Black_VASMJ04MAnKBL001nPBL)",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B07D8RSPMQ&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/3jyryMx",
},
{
        id:11,
        productname:"Fast Fashions Women's Georgette Semi-stitched Indo-Western (White, Pink, Free Size)",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B099J9JCPW&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/3ni0oKW",
},
{
        id:12,
        productname:"Khushal K Women's Rayon Kurta with Palazzo Set",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B07L2ZYJMN&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/30X4gJS",
},
{
        id:13,
        productname:"Dhruvi Trendz Women's Linen Cotton Silk Printed Diwali Special New Saree with blouse piece",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B0922V9KCQ&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/3GexnbN",
},
{
        id:14,
        productname:"MIMOSA Women's Kanchipuram Silk Saree With Un-stitched Blouse (161-BLK-RD_Black)",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B01JUQL4KE&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/3m6Ovbg",
},
{
        id:15,
        productname:"Florely Women's Anarkali Long Gown With Dupatta",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B08XBNXC42&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/3Gg9fFw",
},
{
        id:16,
        productname:"Ethnic Yard Women's Silk Semi Stitched Anarkali Gown(SSEY-F1273_Turquoise_Free Size)",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B07S1J8DYW&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/3m59tHE",
},
{
        id:17,
        productname:"Riddhi Imperial® Women's Woven Banarasi Art Silk Peacock Zari Design Silk Amazing Saree for Diwali Special With Unstitched Blouse Piece Designer Saree for Party & Get Together(Teal Green Color)",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B09JSXNY2H&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/3nkTdBS",
},
{
        id:18,
        productname:"OM SAI LATEST CREATION Designer Slub Rayon Fully Stitched Anarkali Kurti for Women & Girls on Jeans Palazzo or Skirt (Plus Size Upto 2XL)",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B08QZCZPLT&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/3m79wT9",
},
{
        id:19,
        productname:"ANNI DESIGNER Women's Ruby Cotton Foil Printed Straight Kurta with Palazzo & Dupatta (Kashmiri-Blue)",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B097C5K37P&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/3nl892F",
},
{
        id:20,
        productname:"Shiva Fab Short Kurti for Women | Embroidered Straight Rayon Kurta | Round Neck Full Sleeves Short Kurti for Women's",
        productimage:"//ws-in.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B097T1KT4Q&Format=_SL250_&ID=AsinImage&MarketPlace=IN&ServiceVersion=20070822&WS=1&tag=malavmori2006-21&language=en_IN",
        arondprice:"650",
        categories:"cloth",
        productlink:"https://amzn.to/3Ggaa8W",
},
]

export default productdata;